//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using System;
using APE.Umbraco;
namespace RhinoTech.App.Classes.Cms
{
    public partial class NewsItem : Viewmaster
    {

		public NewsItem(): base()		
		{
			this.Header = new StringProperty(){ Alias = "header" };
			this.ShortDescription = new StringProperty(){ Alias = "shortDescription" };
			this.Date = new DateTimeProperty(){ Alias = "date" };
			this.BodyText = new StringProperty(){ Alias = "bodyText" };
				
		}

		[Obsolete("Use the implicit operator... Just remove the .DocTypeAlias")]
		new public readonly string DocTypeAlias = "NewsItem";

		public static implicit operator string(NewsItem doctype)
		{
			return "NewsItem";
		}
	 		
				
		/// <summary>
		///		<para>Datatype: Textstring</para>
		/// </summary>
		public StringProperty Header { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Textbox multiple</para>
		/// </summary>
		public StringProperty ShortDescription { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Date Picker</para>
		/// </summary>
		public DateTimeProperty Date { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Default Editor Grid</para>
		/// </summary>
		public StringProperty BodyText { get; private set; }
	}
}
