//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using System;
using APE.Umbraco;
namespace RhinoTech.App.Classes.Cms
{
    public partial class ProductManagement : Viewmaster
    {

		public ProductManagement(): base()		
		{
			this.Header = new StringProperty(){ Alias = "header" };
			this.ShortDescription = new StringProperty(){ Alias = "shortDescription" };
				
		}

		[Obsolete("Use the implicit operator... Just remove the .DocTypeAlias")]
		new public readonly string DocTypeAlias = "ProductManagement";

		public static implicit operator string(ProductManagement doctype)
		{
			return "ProductManagement";
		}
	 		
				
		/// <summary>
		///		<para>Datatype: Textstring</para>
		/// </summary>
		public StringProperty Header { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Textbox multiple</para>
		/// </summary>
		public StringProperty ShortDescription { get; private set; }
	}
}
