

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
namespace RhinoTech.App.Classes.Cms
{
    public static class DocTypes
    {
        private static Viewmaster _Viewmaster;
        public static Viewmaster Viewmaster
        {
            get { return _Viewmaster ?? (_Viewmaster = new Viewmaster()); }
        }
        private static Frontpage _Frontpage;
        public static Frontpage Frontpage
        {
            get { return _Frontpage ?? (_Frontpage = new Frontpage()); }
        }
        private static TextPage _TextPage;
        public static TextPage TextPage
        {
            get { return _TextPage ?? (_TextPage = new TextPage()); }
        }
        private static Warehouse _Warehouse;
        public static Warehouse Warehouse
        {
            get { return _Warehouse ?? (_Warehouse = new Warehouse()); }
        }
        private static ContactPage _ContactPage;
        public static ContactPage ContactPage
        {
            get { return _ContactPage ?? (_ContactPage = new ContactPage()); }
        }
        private static IntranetHome _IntranetHome;
        public static IntranetHome IntranetHome
        {
            get { return _IntranetHome ?? (_IntranetHome = new IntranetHome()); }
        }
        private static ProductManagement _ProductManagement;
        public static ProductManagement ProductManagement
        {
            get { return _ProductManagement ?? (_ProductManagement = new ProductManagement()); }
        }
        private static NewsSection _NewsSection;
        public static NewsSection NewsSection
        {
            get { return _NewsSection ?? (_NewsSection = new NewsSection()); }
        }
        private static NewsItem _NewsItem;
        public static NewsItem NewsItem
        {
            get { return _NewsItem ?? (_NewsItem = new NewsItem()); }
        }
        private static EditProduct _EditProduct;
        public static EditProduct EditProduct
        {
            get { return _EditProduct ?? (_EditProduct = new EditProduct()); }
        }
    }
}

// Generated helper templates
// Generated items
// RhinoTech\RhinoTech\RhinoTech.App\Classes\Cms\EditProduct.cs
// RhinoTech\RhinoTech\RhinoTech.App\Classes\Cms\NewsItem.cs
// RhinoTech\RhinoTech\RhinoTech.App\Classes\Cms\NewsSection.cs
// RhinoTech\RhinoTech\RhinoTech.App\Classes\Cms\ProductManagement.cs
// RhinoTech\RhinoTech\RhinoTech.App\Classes\Cms\IntranetHome.cs
// RhinoTech\RhinoTech\RhinoTech.App\Classes\Cms\ContactPage.cs
// RhinoTech\RhinoTech\RhinoTech.App\Classes\Cms\Warehouse.cs
// RhinoTech\RhinoTech\RhinoTech.App\Classes\Cms\TextPage.cs
// RhinoTech\RhinoTech\RhinoTech.App\Classes\Cms\Frontpage.cs
// RhinoTech\RhinoTech\RhinoTech.App\Classes\Cms\Viewmaster.cs
