

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
namespace RhinoTech.App.Classes.Cms
{
    public static class DocTypes
    {
        private static Viewmaster _Viewmaster;
        public static Viewmaster Viewmaster
        {
            get { return _Viewmaster ?? (_Viewmaster = new Viewmaster()); }
        }
        private static Frontpage _Frontpage;
        public static Frontpage Frontpage
        {
            get { return _Frontpage ?? (_Frontpage = new Frontpage()); }
        }
        private static TextPage _TextPage;
        public static TextPage TextPage
        {
            get { return _TextPage ?? (_TextPage = new TextPage()); }
        }
    }
}

// Generated helper templates
// Generated items
// RhinoTech\RhinoTech\RhinoTech.App\Classes\Cms\TextPage.cs
// RhinoTech\RhinoTech\RhinoTech.App\Classes\Cms\Frontpage.cs
// RhinoTech\RhinoTech\RhinoTech.App\Classes\Cms\Viewmaster.cs
