//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using System;
using APE.Umbraco;
namespace RhinoTech.App.Classes.Cms
{
    public partial class Viewmaster 
    {

		public Viewmaster()		
		{
				
		}

		public readonly string DocTypeAlias = "Viewmaster";

		public static implicit operator string(Viewmaster doctype)
		{
			return "Viewmaster";
		}
	 
	}
}
