//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RhinoCRM.Core.Entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companys
    {
        public Companys()
        {
            this.Customers = new HashSet<Customers>();
        }
    
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public int Postalcode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<Customers> Customers { get; set; }
    }
}
