//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RhinoCRM.Core.Entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrdersItems = new HashSet<OrdersItems>();
            this.WarehouseShelfs = new HashSet<WarehouseShelfs>();
        }
    
        public int ID { get; set; }
        public string SKU { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public bool Discontinued { get; set; }
    
        public virtual ICollection<OrdersItems> OrdersItems { get; set; }
        public virtual ICollection<WarehouseShelfs> WarehouseShelfs { get; set; }
    }
}
